# Generated by Django 2.2.11 on 2020-05-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon',
            new_name='Coupons',
        ),
    ]
