# Generated by Django 2.2.11 on 2020-05-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusinformation',
            name='time',
        ),
    ]
