# Generated by Django 2.2.11 on 2020-05-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200509_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='appartment_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
