# Generated by Django 2.2.11 on 2020-05-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200508_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
