# Generated by Django 2.2.11 on 2020-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200509_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_on_arrival',
            field=models.BooleanField(default=False),
        ),
    ]
