# Generated by Django 2.2.11 on 2020-05-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20200507_0000'),
        ('orders', '0011_order_pay_on_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.Coupon'),
        ),
    ]
