# Generated by Django 2.2.11 on 2020-05-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='popular_item',
            field=models.BooleanField(default=False),
        ),
    ]
