# Generated by Django 2.2.11 on 2020-05-07 19:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200507_0144'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
