# Generated by Django 2.2.11 on 2020-05-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200507_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created',)},
        ),
    ]
