# Generated by Django 2.2.11 on 2020-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200508_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='product_avatar.jpg', upload_to='products/'),
        ),
    ]
